### ISSUE TITLE
这样怎么在runtime解决呢？

### ISSUE THREAD

**Issue by xhzengAIB** [JazysYu/JZNavigationExtension#1]
![bug](https://cloud.githubusercontent.com/assets/1969908/8426059/fa3f9c26-1f3e-11e5-9bf2-7dc1b6ca92d6.gif)

**Comment by JazysYu** [comment]
Hi,什么问题？

**Comment by xhzengAIB** [comment]
Hi！@JazysYu 

其实就是在某个页面把导航栏隐藏，然后手势返回的时候，导航栏不会跟着手势显示出来

Jack

**Comment by JazysYu** [comment]
你调节的是导航栏的背景透明度，而不是隐藏导航栏哈

**Comment by xhzengAIB** [comment]
可能是我描述有误

总结：导航栏的透明度和手势怎么挂钩

**Comment by JazysYu** [comment]
明白你的意思了，你是想每个控制器的导航栏透明度不同，通过手势产生做渐变效果，这个目前版本是没有的，因为导航栏是全局的，不属于某一个控制器，感谢你的comment，如果可能的话我会在新版本中增加。

**Comment by JazysYu** [comment]
你目前可以禁用掉导航栏全透明的那个控制器的手势来规避这个问题。

**Comment by xhzengAIB** [comment]
如果某个业务需要把单个页面的导航栏改为 透明的，那就规避不了了

**Comment by JazysYu** [comment]
把你需要导航栏透明的那个控制器的Pop手势关闭掉。

**Comment by JazysYu** [comment]
目前这个框架没有按你说的功能那样去设计。

**Comment by xhzengAIB** [comment]
好的！  谢谢你热心的回复，那我把Issue关了吧！

**Comment by vvlee** [comment]
我现在业务上也碰上了这个问题，两个界面的导航栏透明度不同，甚至二级界面的透明度还是动态变化的，所以手势pop的时候，导航栏的颜色就各种幻化。。。

**Comment by JazysYu** [comment]
升级到1.2试一试

**Comment by vvlee** [comment]
下午有升级到1.2，效果是一样的，这个框架能不能在手势pop的时候，各viewController的navigationBar效果独立显示，而不是有一个过渡效果？

现在的情况：二级viewController的bar alpha有变动之后，滑动返回bar自动全透明，而rootViewController也在viewDidAppear(viewWillAppear）里设置了不透明。
总结：两个viewController的navigationBar color或者alpha不一致，滑动时navigationBar的过渡效果就会显得比较诡异
