### ISSUE TITLE
取消了这个setInteractivePopGestureRecognizerCompletion方法了吗？

### ISSUE THREAD

**Issue by lianleven** [JazysYu/JZNavigationExtension#13]
- (void)setInteractivePopGestureRecognizerCompletion:(void (^)(BOOL finished))completion;没有找到替代方法，不知道是去掉了还是？

**Comment by JazysYu** [comment]
没有取消

**Comment by lianleven** [comment]
嗯嗯，我看了一下版本，pod下来的版本是1.2.6的，当前版本是1.3.1的。pod search出来的是1.2.6版本的

**Comment by JazysYu** [comment]
我这边search出来的是1.3.1的，你再试试呢？

**Comment by lianleven** [comment]
我search出来的还是1.2.6版本的，是因为没有更新pod的本地仓库吗？开vpn，pod update很久了还没有更新

**Comment by lianleven** [comment]
我更新了一下pod，现在search出来的是1.3.2最新的。谢谢。
