### ISSUE TITLE
旧版切换到新版出现问题

### ISSUE THREAD

**Issue by MrCoderMSH** [JazysYu/JZNavigationExtension#15]
旧版本的NavigationBar的颜色是黑色正常，JZNavigationExtension切换到目前最新版后NavigationBar的颜色变为白色了，望解答，是我使用姿势不正确么？谢谢

**Comment by MrCoderMSH** [comment]
重要的是：在iOS8以上设备使用UITableView的-(NSArray *)tableView:(UITableView *)tableView editActionsForRowAtIndexPath:(NSIndexPath *)indexPath方法进行左滑事件时会在pop回页面时失效，希望可以解决哈~~~而且经常push不到新页面  去掉JZNavigationExtension时这些症状都消失/(ㄒoㄒ)/~~

**Comment by JazysYu** [comment]
明天跟一下这两个问题

**Comment by MrCoderMSH** [comment]
紧急等待修复~~话说我进入一个视图控制器时设置的self.navigationController.navigationBarBackgroundAlpha = 0;scrollview上滑的时候动态设置navigationBarBackgroundAlpha来实现的Parallax效果，是不是因为这个问题导致内存开销了呢？

**Comment by JazysYu** [comment]
你可以先切到上一个版本，最新的代码并没有加到pod里，先尽量用release的版本

**Comment by MrCoderMSH** [comment]
上一版本也存在push的时候偶尔失效，push不过去，不知道是不是我的使用上有什么问题呢，谢谢

**Comment by JazysYu** [comment]
如果你说的有时候push不过去是你之前说的问题导致的我会尽早抽时间看一下，否则我这边没遇到过这种情况。

**Comment by MrCoderMSH** [comment]
貌似找到push失效的原因了，要在fromVC里面设置当前的fullScreenInteractivePopGestureRecognizer=NO;已经完全避免了push失效的重现

**Comment by MrCoderMSH** [comment]
已证实fullScreenInteractivePopGestureRecognizer=YES时push会出现失败以及cell左滑编辑等操作失效。

**Comment by JazysYu** [comment]
什么使用情况？用到什么控件？

**Comment by MrCoderMSH** [comment]
UITableView cell点击进行跳转 以及cell左滑等事件

**Comment by JazysYu** [comment]
没有复现你说的问题，你可以写个Demo发给我看看。

**Comment by zhenhuamu** [comment]
旧版本的NavigationBar的颜色是黑色正常，JZNavigationExtension切换到目前最新版后NavigationBar的颜色变为白色了 这个问题 是怎么解决的？

**Comment by JazysYu** [comment]
看下你的导航栏style要用black

**Comment by JazysYu** [comment]
你好，试一下1.4.0版。
