### ISSUE TITLE
setInteractivePopGestureRecognizerCompletion这个方法是和navigationController的生命周期绑定的

### ISSUE THREAD

**Issue by lianleven** [JazysYu/JZNavigationExtension#16]
描述：当在一个controller中调用setInteractivePopGestureRecognizerCompletion它时，发现在同一个navigationController中，任何一个滑动返回都会掉用这个方法。

我试着在这个setInteractivePopGestureRecognizerCompletion完成时，用navigationController.interactivePopedViewController来获取当前的controller做判断，但是获取不到这个controller。

**Comment by JazysYu** [comment]
是的，这个回调是不区分controller的，你可以在不想使用block的地方重新将block置空，或者在完成时判断导航控制器的visibleviewcontroller

**Comment by JazysYu** [comment]
你好，1.3.4里 "setInteractivePopGestureRecognizerCompletion"现在提供更多参数返回在block中，你可以使用poppedViewController/visibleViewController/interactivePopedViewController三个属性来判断当前的控制器。
