### ISSUE TITLE
push以后bar变成白色的了

### ISSUE THREAD

**Issue by hongdong** [JazysYu/JZNavigationExtension#18]
push以后bar变成白色的了，望解答

**Comment by hongdong** [comment]
紧急问题、目前使用的是1.3.3最新版

**Comment by JazysYu** [comment]
初始化导航控制器时调用导航栏的setBarStyle : black

**Comment by JazysYu** [comment]
你可能是通过设置的bar tint color把导航栏变成黑色的，1.3.3让导航栏变为黑色推荐设置barStyle，如果想变成其他默认颜色的话，就pull一下最新代码，稍后等我测试通过后会更新到pod中。

**Comment by hongdong** [comment]
恩、是的、我是通过全局的bar tint color把bar设置成主题色的，barStyle的设置并不符合需求，谢谢，等待更新中

**Comment by JazysYu** [comment]
嗯，你更新到新的1.3.4试下吧

**Comment by hongdong** [comment]
1.3.4版本 第一次push过去以后没有问题、退回来以后bar会变成黑色、再push过去也是黑色、

**Comment by JazysYu** [comment]
没明白你的意思，你想要黑色的不是正确的？

**Comment by hongdong** [comment]
![2016-01-30 21_28_35](https://cloud.githubusercontent.com/assets/5499518/12695974/82a9f24e-c798-11e5-89f9-5b88c4dece18.gif)
我设置的bar tint color是我自己的主题色，在baseNavgationVC里面统一设置的，但是push过去再退回来就变成黑色了

**Comment by hongdong** [comment]
![2016-01-30 21_31_52](https://cloud.githubusercontent.com/assets/5499518/12695993/f2ceb82a-c798-11e5-99e2-a3d7f1c14381.gif)

**Comment by JazysYu** [comment]
在你设置完导航栏主题颜色之后，把你首页控制器的navigationBarTintColor属性也设置成你的主题颜色试试

**Comment by hongdong** [comment]
恩、我试了一下、按照你说的这样是可以的、就是在delegate中设置[[UINavigationBar appearance] setBarTintColor:THEME_COLOR];这种方式是不行的，为什么呢？

**Comment by JazysYu** [comment]
控制器的navigationBarTintColor属性是懒加载的，你设置的颜色代码要晚于懒加载的代码，所以你的首页控制器读取导航栏颜色时其实还没有颜色。这块看来还是要优化一下

**Comment by JazysYu** [comment]
@hongdong 我这边在导航控制器的ViewDidLoad中设置导航栏颜色的话没有复现你的问题，你是在哪设置的[[UINavigationBar appearance] setBarTintColor:THEME_COLOR];？

**Comment by JazysYu** [comment]
你好，新版的行为已经改变
