### ISSUE TITLE
第一次push总是出错

### ISSUE THREAD

**Issue by Z-JaDe** [JazysYu/JZNavigationExtension#19]
项目结构window-----navVC------tabbarVC。
我的首页的navigationBarBackgroundAlpha是会随着滚动变化的，默认第一次进入为0；
今天我发现，当我第一次进入应用，在不滚动的情况下，只点击了一个searchTitleView，第一次push时，push出的VC无论设置成什么值，第一次alpha总是和首页的alpha相同。

**Comment by Z-JaDe** [comment]
进过多次调试终于找到答案，有点蛋疼，原来第一次触碰屏幕时，无论是否拖动，都会自动调用一次scrollViewDidScroll，导致第一次push无论设置什么值，都会被scrollViewDidScroll里面那个设置alpha的代码重置回来。

**Comment by JazysYu** [comment]
你也许可以在scrollViewDidScroll里做下判断再设置alpha值呢？比如在contentOffset达到一定值以后再进行设置。

**Comment by Z-JaDe** [comment]
我已经这样做了，谢谢
