### ISSUE TITLE
拖动手势影响到navBar的正常显示

### ISSUE THREAD

**Issue by guiqiang107** [JazysYu/JZNavigationExtension#2]
当第一个controller隐藏NavBar,push到第二个controller(第二个controller不隐藏navBar),向下或向上任意拖动一下（不pop到第一个controller），第二个controller的NavBar被一块黑色（或白色）的替代了

**Comment by JazysYu** [comment]
非常感谢你的issue，隐藏NavBar调用的什么方法？

**Comment by JazysYu** [comment]
你好，一直没有复现你的问题，我已经推出了新版本，感谢issue。
