### ISSUE TITLE
导航栏滑动返回效果

### ISSUE THREAD

**Issue by j364960953** [JazysYu/JZNavigationExtension#20]
请问，（斗鱼TV和网易新闻页面pop切换效果）那种有导航栏的返回动画效果怎么做的呢？本级导航栏滑动返回的时候（pop），跟上一级的导航栏感觉是独立的效果，这个支持吗

**Comment by JazysYu** [comment]
那种效果我觉得是两个导航栏

**Comment by j364960953** [comment]
@JazysYu 请问怎么才能实现两个导航栏吗，您这个可以实现吗，有哪些好的框架呀，多谢了！

**Comment by JazysYu** [comment]
这个应该不用框架就可以做，有一个想法你可以试一下，你push的时候new一个导航控制器，设置它的rootVC为你想要的控制器，然后你直接push那个导航控制器试试

**Comment by j364960953** [comment]
这样是不行的，会直接崩溃了。。导航控制器不能直接push到导航控制器呀

**Comment by JazysYu** [comment]
对。网易新闻的每个页面的导航栏都像是独立的，你也许可以在你的父控制器里，加个假的导航栏，再把原本的导航栏隐藏

**Comment by loveuqian** [comment]
@j364960953 
https://github.com/vinqon/MultiLayerNavigation
我使用了这个完成了斗鱼的效果

**Comment by JazysYu** [comment]
嗯。1.5.0已经集成了这个功能。
