### ISSUE TITLE
在translucent为NO的情况下，不需要设置navigationBar.alpha 为0.9吧？

### ISSUE THREAD

**Issue by developforapple** [JazysYu/JZNavigationExtension#21]
你这里设置为0.9是为何？

**Comment by developforapple** [comment]
虽然iOS7后面的版本中translucent默认为YES，但是如果手动设置为NO了，使用JZNavigationExtension会导致push到新的控制器中，它的导航栏带了0.9的透明度，模拟了translucent为YES的情况。这与手动设置translucent为NO相违背，导致导航栏颜色发生变化。

**Comment by JazysYu** [comment]
你好，新的版本已经没有这个问题。
