### ISSUE TITLE
fullScreenInteractivePopGestureRecognizer 设置为YES 后，push后的页面，按钮相关高亮状态失效

### ISSUE THREAD

**Issue by jxaufang168** [JazysYu/JZNavigationExtension#23]
fullScreenInteractivePopGestureRecognizer 设置为YES 后，
push后的页面，页面中有按钮，按钮相关高亮点击状态失效。

**Comment by jxaufang168** [comment]
1.3.4 Demo 中的 UITableView UITableViewCell高亮状态也失效了，跟全屏返回手势有冲突。

**Comment by JazysYu** [comment]
你好，1.4.0已经解决这个问题。
