### ISSUE TITLE
堆栈问题

### ISSUE THREAD

**Issue by Z-JaDe** [JazysYu/JZNavigationExtension#24]
如果我用了- (void)setViewControllers:(NSArray *)viewControllers animated:(BOOL)animated方法，设置堆栈，推出的VC上面经常会出现白条，我又模仿你其他的push方法，把这个setViewControllers方法也重写了一下，没事了。
但是我发现如果我用setViewControllersse后，快速推出栈的话界面很容易报Thread 1:EXC_BAD_ACCESS(code=1,address=0x10)错误，是不是block出现问题了

**Comment by JazysYu** [comment]
你好，白条的问题倒没有复现，不过1.4.0版本增加了setViewControllers: animated:completion接口。感谢issue。

**Comment by Z-JaDe** [comment]
那就可以了，白条只有我在重置了viewControllers数组后，调用setViewControllers:animated方法，才会出现，如果把setViewControllers:animated方法重写就没事了。而且报野指针错误，我也发现了，是我的问题（jpush推送设置回调方法后，回调找不到我己经推出的vc了，不过我也从这里学到了僵尸对象的用法）。
