### ISSUE TITLE
V1.4.0 最新版本，启用相机presentViewController出现白色导航条

### ISSUE THREAD

**Issue by jxaufang168** [JazysYu/JZNavigationExtension#26]
V1.4.0 最新版本，启用相机presentViewController出现白色导航条

一开始以为我自己的库有问题，找了很久，怎么出现一个白色导航
把附件的中的两个类，覆盖最新Demo中的，点击 相机 按钮，就可以重现这个bug
[Uploading ViewController.zip…]()

**Comment by JazysYu** [comment]
好像附件没有传上来，你是用的系统的AVCaptureVideoPreviewLayer？

**Comment by jxaufang168** [comment]
在V1.4.0 demo首页，写个按钮，启动系统自带的相机，出现导航白条。
如果ViewController 是继承UINavigationController的，presentViewController到那个页面都会有这个问题。没有加导航，出现一个白条在上面。
UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init]; imagePicker.modalPresentationStyle= UIModalPresentationOverFullScreen;
imagePicker.delegate = self;
imagePicker.sourceType = UIImagePickerControllerSourceTypeCamera;
imagePicker.mediaTypes = @[(NSString *)kUTTypeImage];
imagePicker.allowsEditing = YES;
[self presentViewController:imagePicker animated:YES completion:NULL];

**Comment by JazysYu** [comment]
你好，这个bug已经在1.4.5中修复了

**Comment by jxaufang168** [comment]
牛，谢谢你的分享。

**Comment by JazysYu** [comment]
不客气
