### ISSUE TITLE
V1.4.1在进入到一个VC的时候马上push到下一个VC，之前设置好的bartintcolor就会丢掉

### ISSUE THREAD

**Issue by hongdong** [JazysYu/JZNavigationExtension#27]
V1.4.1在进入到一个VC的时候马上（在viewDidLoad或者viewDidAppear中）push到下一个VC，之前设置好的bartintcolor就会丢掉，延迟一会再push就没有问题，是不是bartintcolor在比较迟的生命周期函数才设置的。

**Comment by hongdong** [comment]
还有在demo中点击设置bartintcolor那个会报错，倒数第二行

**Comment by JazysYu** [comment]
问题的原因是push比较快的话，控制器的navigationController为nil。已经修复了，但是推荐不要在viewDidLoad里就push到新的控制器，毕竟导航栏共用一个，过早push的话导航栏也许会有突变。
