### ISSUE TITLE
-UINavigationBar sizeThatFits:

### ISSUE THREAD

**Issue by aronspringfield** [JazysYu/JZNavigationExtension#3]
Using this extension with AviarySDK photo editing tools causes broken UINavigationBar layouts that don't respond or in other cases it will crash. 

Commenting out the method UINavigationBar sizeThatFits: fixes the issue. 

![screen shot 2015-07-16 at 09 44 24](https://cloud.githubusercontent.com/assets/12999238/8718837/479c2fc2-2b9f-11e5-813f-2559d69b259f.png)

**Comment by JazysYu** [comment]
Got it! May be AviarySDK do something adjust to navibar,I'll fix it as soon as possible! thx.

**Comment by aronspringfield** [comment]
I'll put any fix in straight away and let you know how it goes. Thanks

**Comment by aronspringfield** [comment]
Just a little extra information, I have found similar issues with the UIToolbar sizeThatFits when using a WebView.

**Comment by JazysYu** [comment]
Yeap,they are in the same case,I will fix them together.

**Comment by JazysYu** [comment]
I should have fixed this issue. You may try my latest check-in and confirm me whether it fixes your problem. I'll release a new build if it really fixes the issue.

**Comment by aronspringfield** [comment]
Yeah this seems to be fixed. Thanks

**Comment by JazysYu** [comment]
Fine, the new version 1.2.1 has been pushed to CocoaPods.Thanks for your issue :-)
