### ISSUE TITLE
快速来回切换视图会有问题

### ISSUE THREAD

**Issue by ac1217** [JazysYu/JZNavigationExtension#31]
快速切换push跟pop导航条会变白色，应该是自动隐藏了

**Comment by JazysYu** [comment]
不太清楚快速push跟pop是什么意思，是过早时机push？试一试1.4.5有没有解决你的问题。

**Comment by Tracydeng** [comment]
这个问题我也遇到过，应该是短时间内多次调用  ：  [self setNavigationBarHidden:!toViewController.jz_wantsNavigationBarVisible animated:animated];
这个引起的，造成系统导航栏错乱

**Comment by JazysYu** [comment]
之前有一个类似的issue，原因是：toViewController.jz_wantsNavigationBarVisible在控制器还没有导航控制器之前设置会把隐藏导航栏。这个问题已经修复了。你看看最新版还有没有这个问题了。

**Comment by zhouwude** [comment]
这个问题在最新版本当中也遇到了 点击太快导航栏会变白

**Comment by ac1217** [comment]
还是有这个问题，你试下在2个控制器不断快速来回切换视图就会出现了

**Comment by JazysYu** [comment]
我这边最新的版本一直没有复现，最好能提供一下具体代码，比如你的A、B控制器有没有设置过jz_wantsNavigationBarVisible，以及你是如何快速push、pop的。

**Comment by ac1217** [comment]
没有设置过jz_wantsNavigationBarVisible，并且有时会随机出现，我在viewdidload设置barhidden这样可以吗？

**Comment by JazysYu** [comment]
这几天尝试修改了一下，试下最新代码。
