### ISSUE TITLE
hello><

### ISSUE THREAD

**Issue by j364960953** [JazysYu/JZNavigationExtension#33]
presentViewController 控制器的时候，如何禁用您的黑魔法呢，
比如一个baseNAV 
我想presentViewController到一个新的NAV，如何才能使新的NAV不是baseNAV呢（NAV：导航控制器）

**Comment by JazysYu** [comment]
不太明白为什么新的nav会是baseNav呢？你现在presentViewController到一个新的NAV有什么问题？

**Comment by Asingers** [comment]
@JazysYu  JZNavigationExtension 最低支持iOS版本是多少呢

**Comment by hellerchen** [comment]
大概跟我遇到一样的问题, presentViewController一个UINavicationViewController,这时候怎么禁用你的这个扩展?

**Comment by JazysYu** [comment]
@Asingers  最低iOS7。@hellerchen 提issues直接把遇到了什么问题提出来好吧？
