### ISSUE TITLE
我的问题为什么没了。我就问下这个可以上架吗

### ISSUE THREAD

**Issue by 597579501** [JazysYu/JZNavigationExtension#34]
如题。用起来非常好用也解决了我所有问题。但是发现private。就想问下可以上架不
另外兼容是从多少到多少的

**Comment by JazysYu** [comment]
可以上架哈。兼容iOS7.0-9.3.1，iOS10待验证。

**Comment by 597579501** [comment]
@JazysYu 谢谢你的回复。刚才才在关闭的问题看到。而且你回复的这么快。有心了。昨天被吐槽说不支持ios7.现在ios7的设备很难找。我也没办法验证所以来代码的亲爸爸这验证下

**Comment by JazysYu** [comment]
关于版本支持，我会更新readme
