### ISSUE TITLE
ViewController 的 push 动作navigationBar隐藏消失问题

### ISSUE THREAD

**Issue by SuooL** [JazysYu/JZNavigationExtension#35]
.....整个项目里面的都要改，而且改了之后出现了 navigationBar 消失的问题。

**Comment by JazysYu** [comment]
第一个问题你可以全局搜索替换哈，工程搜索然后选replace。第二个问题你需要给想要导航栏的控制器设置jz_wantsNavigationVisible=true.
最近会写一篇api文档，详细说明一下。

**Comment by SuooL** [comment]
jz_wantsNavigationVisible不是默认显示了么？

**Comment by SuooL** [comment]
现在遇到同 [issue30](https://github.com/JazysYu/JZNavigationExtension/issues/30)类似的问题，在 viewControllerA 中，设置jz_wantsNavigationBarVisible=NO，以及navigationBarHidden=YES，然后 push 进入viewControllerB 中，此时 B 默认隐藏导航条，就算在push  B之前设置jz_wantsNavigationBarVisible=YES，以及navigationBarHidden=NO，push 进入 B 确实显示了，但是在拖动viewControllerB 的时候还是会出现 B 的NavigationBar消失的问题。

**Comment by SuooL** [comment]
这里有个疑问是每个 viewController 的NavigationBar不都是相对独立的么？为什么前面一个 viewController的NavigationBar 属性会影响下一个 push 进来的 viewController 的状态呢？这里是不是我理解错了呢？

**Comment by SuooL** [comment]
![test](https://cloud.githubusercontent.com/assets/6235813/14889615/218c24d8-0d92-11e6-88f8-7a74d6f730bc.gif)
具体问题显示的效果如上面 gif所示，请问这样是我该怎么解决呢？

**Comment by SuooL** [comment]
问题已经解决，这里我的理解是：
1. 旧版的时候，我在APPDelegate 中通过`- (void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated`统一设置navigationController的属性，没有上述问题。
但是新版的这样子做不行了。
2. 新版的设计貌似是想希望要在每个UIViewController设置说明：
`    self.jz_wantsNavigationBarVisible = NO;
    self.navigationController.navigationBarHidden = YES;
    self.navigationController.jz_fullScreenInteractivePopGestureEnabled = NO;`
特别的如上面我的问题，我在viewControllerA中设置了隐藏，那么在 push 进来的每个 viewController 中都要设置对应的属性。不能够在统一的设置了。

**Comment by JazysYu** [comment]
首先感谢你的Issue哈，写的很详细。关于新版与旧版之间的变化，之后我会总结成文档，简单说明一下。你说的关于Issue30的问题我已经理解你的意思了，会尽快看下。
