### ISSUE TITLE
首页的导航栏隐藏不了

### ISSUE THREAD

**Issue by jming0618** [JazysYu/JZNavigationExtension#36]
就是uinavigationController的rootviewController的导航栏隐藏不了

**Comment by JazysYu** [comment]
是，因为rootviewController不是被push进入导航控制器的。你可以在首页控制器的viewDidLoad里加上setNavigationBarHidden:.

**Comment by jming0618** [comment]
这只能暂时隐藏，pop回到首页时导航栏又显示了

**Comment by JazysYu** [comment]
行为修改了一下，你可以下一下最新代码。直接设置jz_wantsNavigationBarVisible就好了，xib也可以。
