### ISSUE TITLE
如何禁用单个viewcontroller的右滑返回呢？

### ISSUE THREAD

**Issue by zengfx** [JazysYu/JZNavigationExtension#37]
如何禁用单个viewcontroller的右滑返回，而不影响其他视图的滑动返回？

**Comment by JazysYu** [comment]
目前没有给每个控制器都区分这个手势，但是你可以在"viewWillAppear"里  "self.navigationController.interactivePopGestureRecognizer.enabled = false;" 等退出控制器再打开。

**Comment by lihj** [comment]
我在viewWillAppear中加了这句话    self.navigationController.interactivePopGestureRecognizer.enabled = false; 
怎么还是可以全屏手势返回呀。

**Comment by lihj** [comment]
BOOL fff = self.navigationController.interactivePopGestureRecognizer.enabled;
我这样断点操作也看到他从原来的YES变成NO了，可是还是可以全屏返回。

**Comment by JazysYu** [comment]
@lihj  目前需要加上jz_fullScreenInteractivePopGestureEnabled = false，下个版本会简化这个行为。
