### ISSUE TITLE
jz_wantsNavigationBarVisible

### ISSUE THREAD

**Issue by cooerson** [JazysYu/JZNavigationExtension#38]
jz_wantsNavigationBarVisible不好用了，手势返回到一半停住，navigationbar就已经完全显示并且覆盖页面了、如果继续放开手势返回（弹回当前页），navigationbar仍然处于显示

**Comment by JazysYu** [comment]
能说的具体一点吗？比如你在哪设置这个属性的？两个控制器是否都显示导航栏？

**Comment by cooerson** [comment]
是的 两个控制器都显示导航栏 切换回1.4.0才正常

**Comment by JazysYu** [comment]
我这里没有遇到你的问题，所以看不懂你的意思，你最好详细说一下在哪设置的属性，以及截屏让我看下现象。

**Comment by cooerson** [comment]
```
 Detail *detail = [self.storyboard instantiateViewControllerWithIdentifier:NSStringFromClass([Detail class])];
        detail.jz_wantsNavigationBarVisible = NO;
        [self.navigationController jz_pushViewController:detail animated:YES completion:^(UINavigationController *navigationController, BOOL finished) {

        }];
```

**Comment by cooerson** [comment]
![Uploading 820756040.png…]()

**Comment by cooerson** [comment]
![1766507520](https://cloud.githubusercontent.com/assets/290716/15165904/3653f224-174c-11e6-96a9-9cacc8c59b75.png)
![820756040](https://cloud.githubusercontent.com/assets/290716/15165914/49584fe6-174c-11e6-96a0-f91698c26b42.png)

**Comment by JazysYu** [comment]
你是在哪里设置“detail”控制器的前一个控制器的jz_wantsNavigationBarVisible的？

**Comment by cooerson** [comment]
没设置呢

**Comment by JazysYu** [comment]
那你有设置过navigationController.navigationBarHidden吗？

**Comment by cooerson** [comment]
也没有呢，那个更奇怪，设置了直接变成黑的

**Comment by JazysYu** [comment]
我说一下我对你这个问题的理解，你现在的现象是，交互detail控制器的POP手势的时候导航栏突然显示出来了，是这个问题吗？我觉得你是不是在哪里设置了没有找到？比如detail控制器有没有在viewWillDisappear方法中设置jz_wantsNavigationBarVisible了，现在需要排查所有设置导航栏隐藏相关的地方。或者你有用到哪个其它库冲突导致的？

**Comment by cooerson** [comment]
解决了，在root nav的viewWillAppear里设置self.jz_wantsNavigationBarVisible = YES;不设置的话navigationBar在pop后就被隐藏了。

**Comment by JazysYu** [comment]
好。有关这个API的特性稍后我会更新一篇文档。

**Comment by cooerson** [comment]
多谢！
