### ISSUE TITLE
navigationBarBackgroundHidden won't recover after ViewController being poped

### ISSUE THREAD

**Issue by xnth97** [JazysYu/JZNavigationExtension#39]
某个 ViewController 的 jz_navigationBarBackgroundHidden 设为 YES 后，之后 pop 或 push 页面的导航栏背景都会消失，而不像之前版本仅会影响该 ViewController。demo 中点击 navigationBarBackgroundHidden 项再返回也是一样，导航栏背景消失。
![simulator screen shot 2016 5 6 5 51 26](https://cloud.githubusercontent.com/assets/6781789/15069870/2b2e782a-13b3-11e6-8266-c59f0592aec7.png)
![simulator screen shot 2016 5 6 5 52 31](https://cloud.githubusercontent.com/assets/6781789/15069903/66cde154-13b3-11e6-901b-cbd501930722.png)

**Comment by JazysYu** [comment]
是的，如果你的控制器没有设置过这个属性，那么它会采用当前该属性的值。比如：A->Push->B，B的jz_navigationBarBackgroundHidden为true，如果你想返回A时显示导航栏背景，那么需要设置A的jz_navigationBarBackgroundHidden为false。

**Comment by xnth97** [comment]
明白了，不过想问下修改成这样的原因是什么呢？

个人感觉原来那种只需要设置当前 ViewController 的逻辑非常直观清晰。改成这样后如果使用 Storyboard 应该也很方便，然而在我的项目中，情况是 A(hidden) 可能 push 到 B,C,D,E,F,G...等等 controller 且并未使用 Storyboard，这样就需要去每个 ViewController 里面都加上和自身逻辑无关的代码。

**Comment by JazysYu** [comment]
https://github.com/JazysYu/JZNavigationExtension/wiki
