### ISSUE TITLE
返回按钮

### ISSUE THREAD

**Issue by q351941406** [JazysYu/JZNavigationExtension#40]
请问如何全局设置Nav的按钮样式呢

**Comment by JazysYu** [comment]
不清楚你说的样式是什么，这个功能不涉及到这个库。如果你要全局设置导航栏按钮的颜色就设置navigationBar的tintColor。另外，[UINavigationBar appearance]方法可以给你一个全局的导航栏让你设置。

**Comment by q351941406** [comment]
好，谢谢

**Comment by JazysYu** [comment]
Welcome
