### ISSUE TITLE
jz_wantsNavigationBarVisible

### ISSUE THREAD

**Issue by zhouwude** [JazysYu/JZNavigationExtension#41]
这个最新版本好像 有问题 在A push 到B的时候， B的jz_wantsNavigationBarVisible改为NO pop回来A的导航也不见了 在老版本中好像 这个还是好使用的

**Comment by zhouwude** [comment]
你是故意改成这样的啊

**Comment by JazysYu** [comment]
https://github.com/JazysYu/JZNavigationExtension/wiki
