### ISSUE TITLE
下一级页面的导航栏标题变成上一级页面的导航栏标题

### ISSUE THREAD

**Issue by jming0618** [JazysYu/JZNavigationExtension#42]
在做项目的时候偶尔出现这种情况。。app退出重启才没问题。

**Comment by jming0618** [comment]
找到问题了。A无导航栏，B无导航栏，C有导航栏，D有导航栏，A->B->C->D,在B的时候右滑，松开，进入C，进入D， D的导航栏会变成C的导航栏。这个问题必现

**Comment by JazysYu** [comment]
你好，非常感谢issue哈，已经更新了代码，看下最新的有没有问题。

**Comment by jming0618** [comment]
你好，更新最新版出现另外一个问题。
首页A无导航栏，B无导航栏，C有导航栏，D有导航栏。A->B->C,在C的时候右滑到B再右滑到A，然后A->D，D的导航栏不见了（APP刚启动A->D，D是有导航栏的）

**Comment by jming0618** [comment]
你好，更新最新版出现另外一个问题。
首页A无导航栏，B无导航栏，C有导航栏。A->B,B右滑到A，然后A->C，C的导航栏不见了（APP刚启动A->C，C是有导航栏的）

**Comment by JazysYu** [comment]
嗯，更新了一下，看下最新的代码。

**Comment by guanzd** [comment]
这个问题在 jz_navigationBarTransitionStyle = JZNavigationBarTransitionStyleDoppelganger 的时候还存在。。。

**Comment by developforapple** [comment]
这个问题目前还存在。

A有导航栏，B有导航栏，C无导航栏，D有导航栏。
A push B push C push D
在D界面使用返回手势，拖拽后取消返回。
然后再次使用手势返回，这次是完成手势。
然后依次手势返回到A界面。
此时，A界面出现了B界面的title和返回按钮。
