### ISSUE TITLE
键盘弹出时候 点击侧滑放回bug

### ISSUE THREAD

**Issue by liujianying** [JazysYu/JZNavigationExtension#43]
键盘弹出侧滑返回，发现键盘被放大了
<img width="270" alt="2016-05-18 5 45 36" src="https://cloud.githubusercontent.com/assets/6265414/15354474/63abbdf4-1d20-11e6-8c7b-e00caed18c79.png">

**Comment by JazysYu** [comment]
你好，我这里没有复现你的问题。
你是分别在哪个方法里弹出、收起键盘的？
你自定义键盘了没有？
