### ISSUE TITLE
导航栏隐藏 bug

### ISSUE THREAD

**Issue by SuooL** [JazysYu/JZNavigationExtension#44]
从 Controller A （隐藏了导航栏）进入搜索 UISearchDisplayController（搜索 Controller），然后搜索push 进入 COntroller B（同样隐藏导航栏），此时拖动 controller B 一段距离后放开（不要返回到 Controller A，依然在 Controller B 中），此时本来 controller B 隐藏的导航栏出现了....

**Comment by SuooL** [comment]
![test](https://cloud.githubusercontent.com/assets/6235813/15733546/70c3983c-28b9-11e6-89f3-a1312af2f825.gif)

示例 gif 如上

**Comment by pinguo-zhangyusheng** [comment]
你的Controller A和Controller B 的 jz_wantsNavigationBarVisible都设置了吗？

**Comment by SuooL** [comment]
设置了..

**Comment by SuooL** [comment]
...没设置会是两条 导航条了，这个 controller 都是我自定义的导航条，把原生的隐藏的了。

**Comment by pinguo-zhangyusheng** [comment]
直接从A Push到B然后重复步骤有没有问题？ 另外你还有没有哪里设置过显示、隐藏导航栏的属性了？
