### ISSUE TITLE
禁用单个viewcontroller的右滑返回问题

### ISSUE THREAD

**Issue by jming0618** [JazysYu/JZNavigationExtension#45]
有A，B，C三个ViewController。A->B,  B在viewWillAppear里self.navigationController.interactivePopGestureRecognizer.enabled = NO;禁止右滑返回，然后B->C后
C的整个界面卡住无反应了。。
（C在viewWillAppear里设置了self.navigationController.interactivePopGestureRecognizer.enabled = YES或B在viewDidDisappear里设置了self.navigationController.interactivePopGestureRecognizer.enabled = YES界面都是卡住的）

**Comment by jming0618** [comment]
Google了下解决了

**Comment by lihj** [comment]
老铁，卡住的问题怎么改的
