### ISSUE TITLE
目前在有tableview的vc里面，触发返回手势太频繁

### ISSUE THREAD

**Issue by Singsmlie** [JazysYu/JZNavigationExtension#46]
如题，本意滑动列表，结果触发了滑动返回，体验并不好，最新的代码如何关闭这个特性

**Comment by loveuqian** [comment]
是的1.4.8之后出现了这个问题

**Comment by JazysYu** [comment]
最新代码已经修复。

**Comment by developforapple** [comment]
可不可以更新下版本。这个手势冲突比较致命。tableView上往不管是上滑还是下滑只要稍微往右侧偏了都会导致滑动停止。

**Comment by loveuqian** [comment]
@developforapple 
用旧版不就好咯
pod 'JZNavigationExtension', '1.4.7'

**Comment by developforapple** [comment]
@loveuqian 
pod 'JZNavigationExtension',:git => 'https://github.com/JazysYu/JZNavigationExtension.git' 使用了最新代码。

**Comment by JazysYu** [comment]
嗯，明天会更新新版，这个bug的修复也在里面，sorry最近时间比较紧。

**Comment by JazysYu** [comment]
新版已经更新
