### ISSUE TITLE
仍然是jz_wantsNavigationBarVisible的问题

### ISSUE THREAD

**Issue by cooerson** [JazysYu/JZNavigationExtension#47]
A设置 self.jz_wantsNavigationBarVisible=yes
B设置 self.jz_wantsNavigationBarVisible=no
A-->B 然后 B返回A，navigation就不见了，这个代码在1.4.7可以用，感觉作者把自己都绕晕。1.4.0那种方法很好，在需要改变navigation的时候才改变，不需要的时候就不需要写多余的东西

**Comment by JazysYu** [comment]
首先我在最新代码里没有复现你的问题，你检查一下哪里设置的这个属性或者有没有其它地方隐藏了导航栏。其次关于这个属性的说明 ： https://github.com/JazysYu/JZNavigationExtension/wiki
