### ISSUE TITLE
现在自定义返回按钮之后 滑动返回就消失了 之前版本没有这个问题

### ISSUE THREAD

**Issue by zhouwude** [JazysYu/JZNavigationExtension#48]

**Comment by JazysYu** [comment]
试下最新代码

**Comment by zengfx** [comment]
我也有这个问题，最新的代码  也没用～但demo可以正常运行

**Comment by JazysYu** [comment]
@zengfx 最新的代码没有更新到Pod里哈。你是怎么自定义的返回按钮呢？

**Comment by zengfx** [comment]
@JazysYu 1.4.7版本可以正常运行，最新的1.4.8反而不行。自定义返回就是父类定义的自定义返回按钮.

`self.navigationItem.leftBarButtonItem = [UIBarButtonItem BarButtonItemWithImage:GetImage(@"nav_pop_normal") highlight:GetImage(@"nav_pop_highlight") target:self action:@selector(popBackAnimated)];`

**Comment by JazysYu** [comment]
用最新的代码试下，不是1.4.8。
