### ISSUE TITLE
push问题

### ISSUE THREAD

**Issue by q351941406** [JazysYu/JZNavigationExtension#52]
点击item快速进去push时，你jz_pushViewController:(UIViewController *)viewController animated:(BOOL)animated completion:(_jz_navigation_block_t)completion 方法内的操作会对导航栏有影响，变成空白栏，如果注释掉一部分代码，只保留[self jz_pushViewController:viewController animated:animated]; 就没问题，希望修复

**Comment by q351941406** [comment]
请尽快修复。。。。。

**Comment by MrCoderMSH** [comment]
同样是这个问题啊
