### ISSUE TITLE
导航栏无法正常显示

### ISSUE THREAD

**Issue by wells1013** [JazysYu/JZNavigationExtension#55]
RootViewController A.jz_wantsNavigationBarVisible = NO, B.jz_wantsNavigationBarVisible = YES
A -> B,B左滑到A,又取消左滑，这个速度比较快，B 的导航栏就会显示不出来了，如下图动画显示
![ddd](https://cloud.githubusercontent.com/assets/5172252/17436467/bbdf10c2-5b49-11e6-8f32-4590af74cf31.gif)

**Comment by wells1013** [comment]
有没有人遇到过同样的问题呢？

**Comment by caprice** [comment]
+1，碰到同样的问题

**Comment by BingTice** [comment]
我新开了issue，找到了原因
