### ISSUE TITLE
感觉很多bug

### ISSUE THREAD

**Issue by q351941406** [JazysYu/JZNavigationExtension#56]
bug 一 ：A push B，B设置VC.jz_wantsNavigationBarVisible = NO;很正常，但是B push C，C就没有导航栏了，这个问题在1.4.0时是不存在的，现在需要手动对C设置jz_wantsNavigationBarVisible = YES才行。
bug 二：A push B，B设置VC.jz_navigationBarBackgroundHidden = YES;A导航栏会闪一下，B 返回 A，A导航栏也会闪，如果是拖动返回的，这种闪更明显，接下来是B push C，C设置jz_navigationBarBackgroundHidden ＝ NO就不行了，在push到C的那一刻导航栏的右边会闪一下，并且内容会比导航栏更早push过去。

PS：A设置的属性是self.jz_wantsNavigationBarVisible = true;
    self.jz_navigationBarBackgroundHidden = NO;

我很喜欢你的框架，希望能尽早修复

**Comment by JazysYu** [comment]
You should read this [https://github.com/JazysYu/JZNavigationExtension/wiki/Welcome-to-the-JZNavigationExtension-wiki!](url) to get the reason for your first bug, it's not real. And I can not reproduce the second one, paste a snapshot may be better. By the way, Please do not use this ambiguous title, try to let people know each concrete ISSUE.

**Comment by q351941406** [comment]
https://github.com/JazysYu/JZNavigationExtension/wiki/Welcome-to-the-JZNavigationExtension-wiki! 这个链接确实能说明bug一，但bug二则不行，这评论怎么上传图片，上传完后preview不显示

**Comment by developforapple** [comment]
bug1:  jz_wantsNavigationBarVisible 是针对单个控制器的。所以如果你没有设置值，那么将不会对导航栏进行隐藏和显示。我采用的解决办法是：建立一个控制器类别，在类别里对viewDidLoad进行swizzling，为jz_wantsNavigationBarVisible设置一个默认值YES。

bug2:  jz_navigationBarBackgroundHidden 的原理是修改navigationBar的backgroundView的alpha值为0，从而实现导航栏背景隐藏效果。你这里闪一下绝对不是因为jz_navigationBarBackgroundHidden导致的。我猜测，你的导航栏的半透明为NO，或者子view的top约束是约束在topLayoutGuide上的，导致B控制器的View没有覆盖到导航栏下面，或者子view没有覆盖到导航栏下面。
建议你使用Xcode，查看运行时的视图层次，确认导航栏下面直接显示的是什么view。

另外：不要什么问题都觉得是BUG，多尝试自己解决。目前而言JZNavigationExtension完善的很好了。
除了一个导致导航栏navigationItem错乱的bug。

**Comment by JazysYu** [comment]
@q351941406 很好，希望你的分类没bug。JZNavigationExtension2也正在开发，会有一套更好的解决方案。

**Comment by wells1013** [comment]
JZNavigationExtension2 会开放吗？

**Comment by pdfun** [comment]
@q351941406 兄弟有开源出来吗。
