### ISSUE TITLE
导航栏隐藏的问题

### ISSUE THREAD

**Issue by q351941406** [JazysYu/JZNavigationExtension#57]
当前控制器的Nav隐藏后，只要一触碰屏幕，我底部的工具条上button的文字和图片就会下移几个像素，这个问题在1.4.0版本上是没有的，我一升级就出现了

**Comment by q351941406** [comment]
self.extendedLayoutIncludesOpaqueBars     = YES;   新版本你估计是用了什么方法隐藏了导航栏，我需要自己手动在隐藏的控制器中加上这行代码约束和绘制才不会冲突，希望你能在框架中加上这个

**Comment by JazysYu** [comment]
隐藏导航栏用的就是系统的setNavBarHidden，检查你的autolayout。另外这个库不支持iOS6导航栏style

**Comment by q351941406** [comment]
我的autolayout根本就没有问题，我知道你用的是系统的setNavBarHidden后，这个方法会影响整个界面的所有相对布局，self.extendedLayoutIncludesOpaqueBars = YES;加上这个就没事了，

**Comment by JazysYu** [comment]
我没办法复现你的问题，不知道你“一触碰屏幕”以后做了什么，如果你的某个View上边距约束的是topLayoutGuide，导航栏隐藏会有影响，这显然是项目的布局方法，在你的项目里解决了不代表可以加到库里。
如果你的导航栏translucent属性为NO，那么会采用iOS6的布局方法，坐标Y以44.为原点，这个库不支持这种方式。

**Comment by q351941406** [comment]
不是，我用的是点坐标系，而且移位的是button里面的文字和图片。button本身没有移动，这可没办法布局的，是它里面的图层动了。你可以加我QQ 3054085881 演示给你看

**Comment by BingTice** [comment]
在你的1.5.0.1的Demo里面，在Style为JZNavigationBarTransitionStyleDoppelganger时。A页面到B页面，B隐藏Bar，在B触发右划返回手势滑动一小部分，再左划或立即取消滑动，此时还在B页面，但本应该隐藏的Bar却显示出来了。我查看了您的源码，在UINavigationController+JZExtension.m里面的self.jz_didEndNavigationTransitionBlock内的本应该执行的语句没能执行，原因是weakSelf.visibleViewController并不是实际展示的B页面，toViewController为A，weakSelf.visibleViewController也为A。应该是UINavigationController本身visibleViewController值变化的延迟。在_JZNavigationInteractiveTransition.m的jz_handleInteractiveTransition Block里面已经拿到了isCancel的值。可否把值传递过去，强制执行未能执行的代码

`if (![toViewController isEqual:weakSelf.visibleViewController]) {
            UIViewController *toViewController = weakSelf.visibleViewController;
            weakSelf.navigationBarHidden = ![toViewController jz_wantsNavigationBarVisibleWithNavigationController:weakSelf];
            weakSelf.jz_navigationBarTintColor = toViewController.jz_navigationBarTintColor;
            weakSelf.jz_navigationBarBackgroundAlpha = [toViewController jz_navigationBarBackgroundAlphaWithNavigationController:weakSelf];
        }`
`if (isCancel) {
        if (navigationController.jz_didEndNavigationTransitionBlock) {
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(self.percentComplete * self.duration * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                if (!navigationController.jz_isInteractiveTransition) {
                    navigationController.jz_didEndNavigationTransitionBlock();
                }
            });
        }
    } else {
        if (navigationController.navigationBar.hidden) {
            navigationController.navigationBarHidden = true;
            navigationController.navigationBar.hidden = false;
        }
    }`

**Comment by q351941406** [comment]
又有新的bug了，在系统的pickerView里进行push选择照片时，再返回就没导航栏了，

**Comment by q351941406** [comment]
我可以通过子类重写push方法，在push中给VC设置显示都不行，在系统的pickerView里点击照片然后编辑，再点取消是没问题的，但如果再编辑是右滑返回就没导航栏了

**Comment by JazysYu** [comment]
Are you talking about UIImagePickerController?

**Comment by q351941406** [comment]
是的

**Comment by JazysYu** [comment]
@interface UIImagePickerController : UINavigationController 

R U trying to push a Navigation Controller????

**Comment by q351941406** [comment]
UIImagePickerController 是prensent出来的，里面还能push

**Comment by JazysYu** [comment]
如果想解决这个issue请尽量写明白些。

**Comment by q351941406** [comment]
我已经说的很明白了UIImagePickerController里点击相册push

**Comment by q351941406** [comment]
UIImagePickerController 是通过present出来的，这是系统的， 你需要在系统里不断push下去，才能选中照片

**Comment by JazysYu** [comment]
Got it, I will fix it next release thx.

**Comment by q351941406** [comment]
你终于明白了，你看我给你提了好多issuse,还有好多个bug呢

**Comment by JazysYu** [comment]
你应该提了三个Issue， #56  #52  这里都没法复现，你有想法也可以pull request 。另外描述问题尽量一次说全，因为我没有你的“上下文”。

**Comment by q351941406** [comment]
#52 在当前版本中已经得到修复，#56问题比较明显，确实很难复现，所以就叫你加我QQ，我远程给你演示看看
