### ISSUE TITLE
1.5.0.1 手势触发返回并取消返回 navigationBar hidden的问题

### ISSUE THREAD

**Issue by BingTice** [JazysYu/JZNavigationExtension#58]
在你的1.5.0.1的Demo里面，在Style为JZNavigationBarTransitionStyleDoppelganger时。
A页面到B页面，B隐藏Bar，在B触发右划返回手势滑动一小部分，再左划或立即取消滑动，此时还在B页面，但本应该隐藏的Bar却显示出来了，并且bar的内容是A的。
我查看了您的源码，在UINavigationController+JZExtension.m里面的self.jz_didEndNavigationTransitionBlock内的本应该执行的语句没能执行。
原因是weakSelf.visibleViewController并不是实际展示的B页面，toViewController为A，weakSelf.visibleViewController也为A。可能是UINavigationController本身visibleViewController值变化的延迟。在_JZNavigationInteractiveTransition.m的jz_handleInteractiveTransition Block里面已经拿到了isCancel的值。可否把值传递过去，强制执行未能执行的代码

。。。。UINavigationController+JZExtension.m。。。。

```
    if (![toViewController isEqual:weakSelf.visibleViewController]) {

        UIViewController *toViewController = weakSelf.visibleViewController;

        weakSelf.navigationBarHidden = ![toViewController jz_wantsNavigationBarVisibleWithNavigationController:weakSelf];

        weakSelf.jz_navigationBarTintColor = toViewController.jz_navigationBarTintColor;

        weakSelf.jz_navigationBarBackgroundAlpha = [toViewController jz_navigationBarBackgroundAlphaWithNavigationController:weakSelf];

    }
```

。。。。_JZNavigationInteractiveTransition.m。。。。

```
    if (isCancel) {

    if (navigationController.jz_didEndNavigationTransitionBlock) {

        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(self.percentComplete * self.duration * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{

            if (!navigationController.jz_isInteractiveTransition) {

                navigationController.jz_didEndNavigationTransitionBlock();

            }

        });

    }

} else {

    if (navigationController.navigationBar.hidden) {

        navigationController.navigationBarHidden = true;

        navigationController.navigationBar.hidden = false;

    }

}
```

**Comment by asiosldh** [comment]
+1

**Comment by JazysYu** [comment]
非常详细，感谢。isCancel确实在早期版本里有，只是后来取消了。这个问题的原因是visibleViewController只返回NavigationController中的"visible view controller"，而当Pop手势触发以后，当前的控制器已经不在"Navigation Stack"中。我会尽快在下个版本统一修复。

**Comment by MrCoderMSH** [comment]
这个问题什么时候能解决呢？版本等着提交、、、、、哭死了
