### ISSUE TITLE
iphone6s设备上出现crash

### ISSUE THREAD

**Issue by MrCoderMSH** [JazysYu/JZNavigationExtension#6]
场景：3d touch某一行cell进行预览将要跳转的新界面，此时偶尔（大概率）会出现crash，提示信息：  this class is not key value coding-compliant for the key __parent

**Comment by JazysYu** [comment]
收到你的问题，拿到机器后会尽快修复，感谢

**Comment by MrCoderMSH** [comment]
还有，就是3d touch跳转到新的视图后全局返回手势失效，仅有左侧边缘右滑返回可以正常使用。。不知道是我姿势不正确呢还是确实有问题

**Comment by JazysYu** [comment]
你好，新版本已经解决了这个问题。
