### ISSUE TITLE
1.5.0.1版本, 手势触发返回,手势失效等问题.

### ISSUE THREAD

**Issue by zhongwuayst** [JazysYu/JZNavigationExtension#62]
A 页面 ( a.jz_wantsNavigationBarVisible = NO )
B 页面 (b.jz_wantsNavigationBarVisible = YES )
A push B , 然后B页面用手势返回，滑动一点然后就不要继续滑动了，同时手指不要离开屏幕。
使得画面上同时A和B页面,  然后再用另一只手去点击屏幕,  条件是另一只手，手指大于等于2的时候，
导航栏消失了。如果这个时候放开手指，能回到A页面那就没问题，但是，如果回不到A页面，而是继续留在B页面，B页面里面的导航栏就消失了，再也无法使用手势了。

测试的代码
    AViewController *a = [AViewController new];
    a.jz_wantsNavigationBarVisible = NO;
    UINavigationController *result = [[UINavigationController alloc] initWithRootViewController:a];
    self.window.rootViewController = result;

必要条件， A是第一个ViewController A的导航必须隐藏， 然后B的导航必须是显示的。
滑动一点就停止，然后用另一只手指 必须手指大于等于2以上去点击。 这是必要条件。

有些情况 比如 A->B->C   B隐藏C显示，这种情况下出现的情况没有A->B情况会无法使用手势问题，导航消失问题还是存在的

**Comment by developforapple** [comment]
一般导航控制器的rootViewController不会隐藏导航栏，所以这个bug还没遇到过。
