### ISSUE TITLE
提交审核，说使用了私有API，被拒

### ISSUE THREAD

**Issue by Tracydeng** [JazysYu/JZNavigationExtension#7]
Non-public API usage:

The app references non-public selectors in Maizuo3.0: _isTransitioning, isInteractiveTransition, navigationTransitionView:didEndTransition:fromView:toView:

**Comment by JazysYu** [comment]
之前没这个问题，回去核实一下如果有问题会全力修复的，感谢

**Comment by Tracydeng** [comment]
很好用的东西，之前版本也是一直有使用，可以提交通过审核的，是昨天在提交到itunesConnect后，构建版本时就会收到邮件提示，然后一直显示正在处理，不能提交审核。

**Comment by JazysYu** [comment]
非常非常感谢，原因还不确定正在排查

**Comment by JazysYu** [comment]
你好，问题应该已经解决了，更新到最新版试下，目前最新版本号是1.2.6

**Comment by Tracydeng** [comment]
可以了，多谢！

**Comment by JazysYu** [comment]
客气了，也非常感谢你
