### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by huxiaoluder** [JazysYu/JZNavigationExtension#70]
我这隐藏导航栏后, 因为 automaticallyAdjustsScrollViewInsets = YES 控制器视图会向上移动导航的高度的距离
但是我看你代码里并没有改动 automaticallyAdjustsScrollViewInsets 的值, 隐藏导航栏后控制器视图也未上移, 也不见你对其 frame 作了修改, 不知道是做了什么样的操作?

**Comment by createname** [comment]
我这里也出现了，视图上移了一段距离，来回拖动几次又自动好了

**Comment by JazysYu** [comment]
#68
