### ISSUE TITLE
iOS Private API Usage

### ISSUE THREAD

**Issue by Sneakr** [JazysYu/JZNavigationExtension#75]
Hello,

Thanks for a good extension. 

However, this is using many many private APIs from "jz_getProperty" methods, and will be rejected by Apple if used. Also, even if it passes the approval, there is a risk that the app will get removed if Apple finds out later case.

**Comment by JazysYu** [comment]
"jz_getProperty" is just a wrapper of "valueForKey:", and is now no longer exist in the latest version(2.0).
