### ISSUE TITLE
ios11 导致leftBarButtonItem点击方法无反应

### ISSUE THREAD

**Issue by Sky-star** [JazysYu/JZNavigationExtension#76]

**Comment by wells1013** [comment]
+1
一样，可有啥办法？

**Comment by Sky-star** [comment]
暂时性的解决办法是将按钮的点击事件更改为touchDown。不过反应有点快，不影响使用。
通过排查大概定位在invoke方法响应。 太复杂了， 我没找到解决办法。

**Comment by zys456465111** [comment]
关于iOS11的适配会在新版本解决，11现在有些特殊目前还有一点问题

**Comment by CallMeLowry** [comment]
！！！  终于找到根源了。  整了大半天，还以为是iOS11的导航栏新特性导致的

**Comment by LittleYuz** [comment]
同样遇到了这个问题，郁闷了半天怎么会出现这种问题😂

**Comment by huanglins** [comment]
我也遇到的同样的问题，自定义导航栏返回按钮后点击失效。我的解决办法是在 BaseViewController 里面加上这两句就OK了：

self.navigationController.interactivePopGestureRecognizer.enabled = YES;
self.navigationController.interactivePopGestureRecognizer.delegate = self;

**Comment by CallMeLowry** [comment]
iOS11中 在 viewWillAppear中 jz_navigationBarBackgroundAlpha = 0，无法将导航栏透明了， 有什么好的解决方法吗

**Comment by Jeff-F** [comment]
@zys456465111 ，请问有新的进展吗 ？ 上线项目用到了这个库适配iOS11有问题 ~

**Comment by zys456465111** [comment]
背景透明还有点问题，考虑先放beta版，如果有想法也欢迎fork

**Comment by liyouleo911** [comment]
@zys456465111 能先放一个解决leftBarButtonItem点击无效的beta吗？

**Comment by hongdong** [comment]
@zys456465111 beta版本的啥时候放出来呢

**Comment by zys456465111** [comment]
个人最近一直时间比较紧，另外我们的项目里不存在这个问题，也是iOS11，新版本换了全新的实现思路，但不确定新版就能解决

**Comment by Jeff-F** [comment]
用Xcode 9以下的版本,不会有这个问题。用xcode 9开发，会有这个问题

**Comment by keepJion** [comment]
if (navigationController.visibleViewController.navigationItem.leftBarButtonItems) {
                            
                            NSArray *leftBarButtonItems = navigationController.visibleViewController.navigationItem.leftBarButtonItems;
                            [invocations addObject:jz_invocation_create(navigationController.visibleViewController.navigationItem, @selector(setLeftBarButtonItems:), &leftBarButtonItems)];
                            navigationController.visibleViewController.navigationItem.leftBarButtonItems = nil;
                        }
我把这里面的代码注释了,然后在下面的方法中单独判断了下来解决的.
- (void)jz_handleNavigationTransitionAnimated:(BOOL)animated fromViewController:(UIViewController *)fromViewController toViewController:(UIViewController *)toViewController transitionBlock:(dispatch_block_t)transitionBlock {
    if(![NSStringFromClass([self class]) isEqualToString:@"BaseNavigationController"]){
        transitionBlock();
        return;
    }
希望能够帮到你们!

**Comment by smartdj** [comment]
#78 
使用这个改法可以临时解决leftBarButtonItem点击没反应问题

**Comment by xiaoer** [comment]
我是继承 一个 BaseNavigationVC 然后 在第一个页面的时候，手势处理一下！

要不有的  leftBarButtonItem 就消失了。
 self.interactivePopGestureRecognizer.delegate = self;
    if([self.navigationController respondsToSelector:@selector(interactivePopGestureRecognizer)])
    {
        self.navigationController.interactivePopGestureRecognizer.enabled = YES;
    }


-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    //判断如果是当前VC是rootVC，直接不响应手势
    if (self.viewControllers.count == 1 ) {
        return NO;
    }
    return YES;
}

**Comment by yilongchun** [comment]
self.navigationItem.leftItemsSupplementBackButton = YES;
加上这句就好了

**Comment by Wangyn19920603** [comment]
在基类里加了这两句就可以了
self.navigationController.interactivePopGestureRecognizer.enabled = YES;
self.navigationController.interactivePopGestureRecognizer.delegate = self;
但是没有弄明白leftbarbutton和手势有什么关系 难道是有手势返回引起的吗？

**Comment by JazysYu** [comment]
导航栏如果没有左侧的backbarbuttonItem就不会响应interactivePopGestureRecognizer，这段逻辑就是由手势的delegate实现。如果delegate = self，要注意处理手势的相关逻辑，否则有可能造成导航栏错乱。
