### ISSUE TITLE
ios11 导航栏透明 只有在viewDidAppear设置有用了

### ISSUE THREAD

**Issue by fantastichong** [JazysYu/JZNavigationExtension#77]
在其他地方设置  然后好像又变成不透明了 感觉内部机制改了  但是在viewDidAppear设置的话 控制器回来的时候会出现闪现的情况

**Comment by CallMeLowry** [comment]
遇到了同样的问题。又不办法直接设navigationBar.alpha为0 。  纳闷

**Comment by yilongchun** [comment]
作者好像都不更新了

**Comment by aslanTT** [comment]
这个怎么解决呢？
@fantastichong  @CallMeLowry  @yilongchun 
你们找到办法了吗？

**Comment by yilongchun** [comment]
@aslanTT ios11 我都显示了导航栏 没有导航栏 适配iphonex 有点丑

**Comment by JazysYu** [comment]
试下新版

**Comment by aslanTT** [comment]
@JazysYu  赞赞赞
