### ISSUE TITLE
2.0，ios9崩溃问题

### ISSUE THREAD

**Issue by tbl00c** [JazysYu/JZNavigationExtension#79]
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<_UINavigationBarBackground 0x15e997300> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _backgroundEffectView.'

**Comment by loupman** [comment]
_backgroundView._backgroundEffectView  只有 iOS10 以后才有的私有属性。 增加如下判断可以解决。
`
- (UIView *)jz_backgroundView {
    if (IOS10Later) {
        return [self valueForKeyPath:@"_backgroundView._backgroundEffectView"];
    }
    UIView *view = [self valueForKeyPath:@"_backgroundView"];
    if (view.subviews.count) {
        return view.subviews.firstObject;
    }
    return view;
}
`

**Comment by tbl00c** [comment]
一个简化过的可用版本
pod 'JZNavigationExtension', :git => 'https://github.com/tbl00c/JZNavigationExtension.git', :tag => '3.7'
