### ISSUE TITLE
在地图的应用场景下

### ISSUE THREAD

**Issue by davieds** [JazysYu/JZNavigationExtension#8]
地图的页面Navigation Hide 了，滑动地图push ViewController 第二个页面的Navigation 也跟着隐藏了 
在push 第二个 ViewController 设置了 显示Navigation  ， 效果没出来

**Comment by JazysYu** [comment]
有个wantsNavigationBar要在push之前设置

**Comment by davieds** [comment]
设置了 

还有个问题就是提交APPstore的问题 ， 使用了私有的API 被拒绝了

We have discovered one or more issues with your recent delivery for "XXX". To process your delivery, the following issues must be corrected:

Non-public API usage:

The app references non-public selectors in XXX: _isTransitioning, isInteractiveTransition, navigationTransitionView:didEndTransition:fromView:toView:
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by JazysYu** [comment]
update到最新版哈，已经有朋友反映这个问题已经解决了。你说的第一个问题还不是太清晰，你试试在其它工程中有没有这个问题
