### ISSUE TITLE
iOS 11 导航栏点击返回按钮，返回按钮上跳

### ISSUE THREAD

**Issue by TonyDark** [JazysYu/JZNavigationExtension#82]
第一个页面时隐藏导航栏，然后第二个页面显示导航栏，页面返回时就会出现上跳。我是自己自定义的UIBarButtomItem ,  iOS 8和9都正常，11就会上跳。
      请问我怎么解决这个问题。项目等着上线，急！

**Comment by TonyDark** [comment]
导航栏都在的页面返回是不会上跳的

**Comment by JazysYu** [comment]
我这里没有复现你的问题，用最新v2.1版试试，另外关闭automaticallyAdjustsScrollViewInsets

**Comment by xiaoklong** [comment]
是存在这样的问题的,在导航控制器的rootViewController点击一下导航栏就会上移消失了

**Comment by JazysYu** [comment]
@TonyDark 1.怎么隐藏的导航栏 2.怎么自定义的barButtonItem

@xiaoklong 确保不是你的项目里其它逻辑在干扰。试着简单描述一下复现步骤或者提供一段伪代码

**Comment by xiaoklong** [comment]
刚刚我尝试了一下,下载你的源代码添加进去是不会的,如果用pod就会,pod好像最新的版本是1.5.0.1版本

**Comment by JazysYu** [comment]
pod repo update 每次更新都会在pod里

**Comment by xiaoklong** [comment]
@JazysYu  你可以试一下,自己pod一下
'''
self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"返回" style:UIBarButtonItemStyleDone target:self action:@selector(ssss)];
'''
点击返回键是无效的,变了颜色会变浅

**Comment by JazysYu** [comment]
@xiaoklong  我尽量快速解决你的问题来避免多给大家发邮件

1. pod 最新版是 2.1
2. 跟一下看看有没有响应到点击事件，必要的话，请把你的"ssss"方法贴出来。

**Comment by TonySDark** [comment]
NSAssert(!self.delegate, @"Set delegate should be invoked when viewDidLoad");这句话奔溃了。我present了一个UIImagePickerController,然后就挂了。是不是present前我需要做什么操作

**Comment by JazysYu** [comment]
设置delegate之前触发一下picker controller的view

**Comment by TonySDark** [comment]
picker controller.view;     这样子？

**Comment by JazysYu** [comment]
对。不知道你的代码，举个例子

UIImagePickerController *imagePickerController = [UIImagePickerController new];
[imagePickerController view];
imagePickerController.delegate = ...;
.... presentViewController:imagePickerController ...;

这里看起来会有比较多的疑问，后续想办法解决下。

**Comment by TonySDark** [comment]
我的代码和你的例子差不多。谢啦
