### ISSUE TITLE
这份fork解决了JZ 2.0的一些bug。

### ISSUE THREAD

**Issue by tbl00c** [JazysYu/JZNavigationExtension#84]
在项目中使用以下语句可替换：
pod 'JZNavigationExtension', :git => 'https://github.com/tbl00c/JZNavigationExtension.git', :tag => '3.7'

这份代码根据我们的业务做了一定简化，没有了Doppelganger这种Style，同时修复了一些bug。
解决的bug包括：
1、ios11以下版本dealloc时KVO未移除导致的崩溃。
2、ios11以下_backgroundEffectView方法不存在导致的崩溃。
3、优化tintColor、alpha、visable等属性的使用逻辑。
4、优化_JZNavigationDelegating中的核心代码，已解决一些页面切换navbar的异常。

JZ的无浸入设计是很赞的，期待作者继续更新。

**Comment by JazysYu** [comment]
最近一直没时间更新，很高兴基于这个库做fork。1、2条已经修复，第3条在wiki里有说明，4的问题出现在部分项目里，还需要花时间在上面。新版的目标是入侵越小越好，结构越简越好。

**Comment by JazysYu** [comment]
2.0.2已经更新。
