### ISSUE TITLE
使用系统UIImagePicker，指定代理方法后，选择相机或者照片，崩溃

### ISSUE THREAD

**Issue by souls-shaohui** [JazysYu/JZNavigationExtension#86]
崩溃日志： Assertion failure in -[UIImagePickerController viewDidLoad], /Users/Documents/Pods/JZNavigationExtension/JZNavigationExtension/UINavigationController+JZExtension.m:54
崩溃指向：
- (void)jz_viewDidLoad {
    NSAssert(!self.delegate, @"Set delegate should be invoked when viewDidLoad");//崩溃在这一句
    self.delegate = nil;
    [self.interactivePopGestureRecognizer setValue:@NO forKey:@"canPanVertically"];
    self.interactivePopGestureRecognizer.delegate = self.jz_navigationDelegate;
    [self jz_viewDidLoad];
}
xcode:9.0.1
ios:10.3.0

**Comment by souls-shaohui** [comment]
你那边可以复现吗

**Comment by JazysYu** [comment]
设置代理要在viewDidLoad后。目前这么做是不想hook更多方法。

**Comment by souls-shaohui** [comment]
我现在把设置代理的方法，放在了点击方法里，还是会造成崩溃。

**Comment by souls-shaohui** [comment]
case 9:
        {
            UIImagePickerController *viewController = [[UIImagePickerController alloc] init];
            viewController.modalPresentationStyle= UIModalPresentationOverFullScreen;
            viewController.sourceType = UIImagePickerControllerSourceTypeCamera;
            viewController.allowsEditing = YES;
            viewController.delegate = self;//我在demo里加了这么一句
            [self presentViewController:viewController animated:YES completion:NULL];
        }
            break;
也会造成崩溃，崩溃信息，也是提示也是代理需要在viewdidload 之后

**Comment by JazysYu** [comment]
在你加的上面加上，[viewCon... view];

**Comment by souls-shaohui** [comment]
我是需要在present之后，再去指定代理吧。

**Comment by souls-shaohui** [comment]
iOS 11 先present 在指定代理 还是会崩溃，

**Comment by JazysYu** [comment]
[self presentViewController:viewController animated:YES completion:^{
                    viewController.delegate = ***;
            }];

Or

[self presentViewController:viewController animated:YES completion:NULL];
            [viewController view];
            viewController.delegate = ***;

**Comment by souls-shaohui** [comment]
恩恩，发现崩溃之后，我就改成这样写的了，但是不知道后续会不会有问题。
