### ISSUE TITLE
在TabBarController下会出现问题

### ISSUE THREAD

**Issue by mrhuangyuhui** [JazysYu/JZNavigationExtension#9]
重现条件：
在TabBarController框架下

重现步骤：
重复点击无NavBar的界面所属的TabBarItem，会出现隐藏的NavBar，详情请见附件。

![screen shot 2015-12-08 at 17 26 24](https://cloud.githubusercontent.com/assets/1132579/11652272/c04ba64c-9dd1-11e5-9c44-50d984b23b81.png)

![screen shot 2015-12-08 at 17 26 31](https://cloud.githubusercontent.com/assets/1132579/11652280/c72679d8-9dd1-11e5-8583-9f6d4d66f0e7.png)

**Comment by JazysYu** [comment]
你可以试一下最新版本 1.2.9

**Comment by btxkenshin** [comment]
@mrhuangyuhui 同样问题，请问解决了么？而且我这儿更奇怪，三个tabitem，其中两个会这样，第一个没事儿

**Comment by btxkenshin** [comment]
问题已解决，需要讲viewcontroller设置wantsNavigationBarVisible=NO

**Comment by pinguo-zhangyusheng** [comment]
@btxkenshin  正解，因为点击tabbarItem会调用导航控制器的popToRootViewController（系统行为），而rootViewController的wantsNavigationBarVisible如果没有设置的话是YES的，所以设为NO就好了。这一点值得优化一下。
